#!/usr/bin/env bash
# Assemble what Vercel serves.
#
#   public/index.html   the shell: chrome and the password box, no data
#   public/app.js       the view code, cacheable, no data
#   api/_payload.json   the data — OUTSIDE public/, so the only way to it is api/data.js,
#                       which checks the session cookie first
#   public/operations/… the two rasters the viewer loads as <img>
#
# The split is generated by the same builder as the local file, so the two cannot drift.
set -euo pipefail

rm -rf public
mkdir -p public/operations/land/geo

# Built here, never committed: a 3.2 MB payload in every commit is how a repository
# gets to 389 MB. Vercel's build image has python3.
command -v python3 >/dev/null 2>&1 || { echo "error: hace falta python3"; exit 1; }
python3 -m sabaleticas map --no-open

cp dashboard/build/index.html   public/index.html
cp dashboard/build/app.js       public/app.js
cp dashboard/build/payload.json api/_payload.json
cp operations/land/geo/orthophoto.jpg   public/operations/land/geo/
cp operations/land/geo/surroundings.jpg public/operations/land/geo/

echo "public/ listo:"
find public api/_payload.json -type f -exec ls -lh {} \; | awk '{print "   "$5"\t"$9}'
